### ISSUE TITLE
i get strange error on android device setup

### ISSUE THREAD

**Issue by volkangurol** [lubritto/Flutter_Medias_Picker#2]
* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'com.android.support:appcompat-v7' has different version for the compile (27.1.0) and runtime (27.1.1) classpath. You should manually set the same version via DependencyResolution

**Comment by volkangurol** [comment]
i changed your dependency lib . implementation to api . and activate multiDexEnabled solves the problem. Can you change  to  api 'com.android.support:appcompat-v7:27.1.1' ?

**Comment by lubritto** [comment]
Hello @volkangurol,

I will change the version of appcompat

**Comment by lubritto** [comment]
Try to adding
implementation 'com.android.support:appcompat-v7:27.1.1 and implementation 'com.android.support:support-v4:27.1.1 to the build.gradle file
