### ISSUE TITLE
Works in debug mode in Android phone but crashes in Release

### ISSUE THREAD

**Issue by sortie** [lubritto/Flutter_Medias_Picker#3]
_From @sureshrr on August 14, 2018 20:16_

URL: https://pub.dartlang.org/packages/pdf_viewer_plugin#-versions-tab-

Worked nicely in development in the virtual device as well as Android phone in debug mode. But when it is deployed in Google play, it installs but when launched,it crashes.
Commented all the code and then also it crashed in Google Play
Finally when it is completely uninstalled in flutter, it doesn't crash.
I love this plugin but why does it crash only on Release.

_Copied from original issue: dart-lang/pub-dartlang-dart#1530_

**Comment by lubritto** [comment]
Can you post the log ? Works nice in here, i need more informations to help you

**Comment by sureshrr** [comment]
When building the code, I see the following errors
Information:8/20/2018 1:29 PM - Compilation completed with 4 errors and 0 warnings in 3 s 23 ms
C:\Java\thuthi\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
Error:(4, 39) java: package io.flutter.plugins.pathprovider does not exist
Error:(5, 35) java: package com.example.pdfviewerplugin does not exist
Error:(15, 5) java: cannot find symbol
  symbol:   variable PathProviderPlugin
  location: class io.flutter.plugins.GeneratedPluginRegistrant
Error:(16, 5) java: cannot find symbol
  symbol:   variable PdfViewerPlugin
  location: class io.flutter.plugins.GeneratedPluginRegistrant
Still it works in Virtual device, but when deployed in Google Play, it crashes on Start up

**Comment by lubritto** [comment]
I'm sorry guys, i put the wrong github path in pdf_viewer_plugin, i will solve this in here, but for the next issues please use https://github.com/lubritto/Pdf_Viewer_Plugin.

I will investigate the problem, what version are you using?

**Comment by sureshrr** [comment]
pdf_viewer_plugin  Version 0.0.4

**Comment by sureshrr** [comment]
Any Update?
