### ISSUE TITLE
Gallery pod Can not build in XCode 10

### ISSUE THREAD

**Issue by volkangurol** [lubritto/Flutter_Medias_Picker#4]
Can you fix pod url?  
https://github.com/hyperoslo/Gallery/issues/123

The master branch already has the fix.
Just need

Change the Podfile with:
pod 'Gallery', :git => 'https://github.com/hyperoslo/Gallery.git', :branch => 'master'.   

Update Swift Language Version with 4.2.  
Go to Xcode -> Choose Pods project -> Choose the Gallery Target -> Choose Buiding Setting tab -> Find the option: Swift Language Version and select 4.2.  
Then the project should be able to compile.  
This works for me.

**Comment by lubritto** [comment]
I will fix that, thanks for the help!

On Sep 22, 2018 22:06, Volkan Gürol <notifications@github.com> wrote:

Can you fix pod url?
hyperoslo/Gallery#123<https://github.com/hyperoslo/Gallery/issues/123>

The master branch already has the fix.
Just need

Change the Podfile with:
pod 'Gallery', :git => 'https://github.com/hyperoslo/Gallery.git', :branch => 'master'.

Update Swift Language Version with 4.2.
Go to Xcode -> Choose Pods project -> Choose the Gallery Target -> Choose Buiding Setting tab -> Find the option: Swift Language Version and select 4.2.
Then the project should be able to compile.
This works for me.

**Comment by lubritto** [comment]
Fixed with version 0.1.1, if the error persists run `pod repo update` and `pod update`, after that if persists open other issue.
