### ISSUE TITLE
Swift Compiler Error with xcode 10

### ISSUE THREAD

**Issue by flowhorn** [lubritto/Flutter_Medias_Picker#6]
Using version 0.1.1 is still get an error with xcode 10. It is related to the SwiftMediasPickerPlugin.
Here is the error message:

> SwiftMediasPickerPlugin.swift:134:37: 'UIImageJPEGRepresentation' has been replaced by instance method >'UIImage.jpegData(compressionQuality:)'

**Comment by lubritto** [comment]
The version 0.1.2 solves the problem, i forgot publish, sorry!
